src/dashboard.py
src/templates/configuration.html
src/templates/get_conf.html

v20210403 Bug Fixed

---

src/dashboard.py

Avoid error when AllowedIps is not defined

---

src/templates/get_conf.html

TOTAL RECIEVED replaced with TOTAL RECEIVED

Update typo3 fix

---

.gitignore

This will use a python virtual environment for this project and make an automated approach for the systemctl unit file. The venv should be ignored within .gitignore as is might be system specific.

An automated way to a systemctl unit

---

src/dashboard.py
src/requirements.txt
src/static/js/configuration.js
src/templates/get_conf.html
src/templates/qrcode.html
src/util.py
src/wgd.sh

Slow Performance Fixed

---

src/dashboard.py

It`s another interpretation of pull request #118
In dashboard.py and get_conf.html different path.

Fixed download configuration file for peer

---

src/dashboard.py

Used  pylint and flake8 for checking

Refactoring

---

README.md
src/dashboard.py
src/requirements.txt

Related to https://github.com/donaldzou/WGDashboard/issues/253

Enabling use of underscores in configuration name

---

src/dashboard.py
src/static/app/src/components/configurationComponents/newPeersComponents/allowedIPsInput.vue
src/static/app/src/components/configurationComponents/peerList.vue
src/static/app/src/views/signin.vue

- Fixed issue in #312: The dashboard will automatically get the actual Dashboard version number.
- Fixed issue in #311: WGDashboard was not treating restricted peers correctly.

Fixed #312, #311

---

src/dashboard.py

Fixed issue where Preshared Key is not added when unrestricted peers

---

src/wgd.sh

Rocky is RHEL compatible like AlmaLinux.

feat: Support Rocky Linux

---

.github/workflows/docker-build.yaml

https://github.com/donaldzou/WGDashboard/issues/377
Reason for merging into main: To fix possible current images.

Added QEMU virtualization for cross-compilation

---

.github/workflows/docker-build.yaml

Specified the QEMU setup. From WireGate
Hi Donald, slight specification to better declare.

Added arm/v6

---

src/dashboard.py

- Fixed `WGDashboard_Backup` not being created and caused crash mentioned in #559

Create WGDashboard_Backup when configuration initialized

---

src/dashboard.py

don't just check for string differences, but compare the version numbering using packaging.version

Fix version checking

---

src/static/locale/active_languages.json
src/static/locale/fa.json

added Farsi language

---

src/dashboard.py
src/static/app/src/components/configurationComponents/editConfiguration.vue
src/static/app/src/views/newConfiguration.vue
src/static/locale/language_template.json

feat: Supporting "table" directive in the configuration

---

src/dashboard.py

Background thread terminated when iterating conf list and list changed

---

.github/workflows/docker.yml

Add a login to the scan

---

src/modules/Email.py

@donaldzou - It looks like you implemented the code great, just noticed the "print" logging which is just extra and I removed it. Let me know if this is acceptable.
It's 830 here and still trying to wake up so the commit message is ugly lol

Removed extra logging for email login

---

docker/Dockerfile-Debian-Slim
docker/README.md
docker/entrypoint.sh
src/modules/AmneziaWireguardConfiguration.py
src/modules/WireguardConfiguration.py

* Add new env vars for docker
* Add email env vars for docker
* Improve sed for email vars
* Refactor entrypoint.sh file
* Add additional account docker vars
* Add comment for clear command

refac: docker entrypoint refactoring (#743) by @AdamGH

---

docker/Dockerfile
docker/README.md
docker/compose.yaml

@donaldzou promoting the GHCR over docker.io

refac(docs): rewrite and check the docker documents

---

.gitignore
src/modules/ConnectionString.py
src/modules/DashboardClients.py
src/modules/DashboardClientsPeerAssignment.py
src/modules/DashboardClientsTOTP.py
src/modules/DashboardConfig.py
src/modules/DashboardLogger.py
src/modules/DashboardWebHooks.py
src/modules/NewConfigurationTemplates.py
src/modules/PeerJobLogger.py
src/modules/PeerJobs.py
src/modules/PeerShareLinks.py
src/modules/WireguardConfiguration.py

fix: https://github.com/WGDashboard/WGDashboard/issues/916
This might be useful if people want to centrally store DB files and manage multiple WGDashboard instances.

feat: add configurable database prefix

---

src/wgd.sh

I don't believe we are using this. So maybe its better we remove it.

refac: remove docker functions
